{{ if .Values.istio.gateway.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: prometeo-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
{{ end }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: prometeo-webapp
spec:
  hosts:
  - "*"
  gateways:
  - prometeo-gateway
  http:
  - match:
    - uri:
        exact: /webapp
    rewrite:
      uri: /
    route:
    - destination:
        host: {{ .Values.webapp.name}}
        port:
          number: {{ .Values.webapp.service.servicePort}}
  - match:
    - uri:
        prefix: /index
    - uri:
        prefix: /admin_bomberos
    - uri:
        prefix: /admin_dispositivos
    - uri:
        prefix: /add_dispositivo
    - uri:
        prefix: /admin_eventos
    - uri:
        prefix: /admin_eventos_form
    - uri:
        prefix: /misalud_estado
    - uri:
        prefix: /misalud_informe
    - uri:
        prefix: /report_mediciones
    - uri:
        prefix: /report_mediciones_new
    - uri:
        prefix: /mapa_evento
    - uri:
        prefix: /testdb
    - uri:
        prefix: /error404
    - uri:
        prefix: /error500
    - uri:
        prefix: /metrics
    - uri:
        prefix: /swagger/api
    - uri:
        prefix: /explorer
    - uri:
        prefix: /assets
    - uri:
        prefix: /dashboard
    route:
    - destination:
        host: {{ .Values.webapp.name}}
        port:
          number: {{ .Values.webapp.service.servicePort}}
